# Generated by Django 5.0.7 on 2024-07-26 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='one',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a1', models.CharField(max_length=20)),
                ('a2', models.CharField(max_length=20)),
                ('a3', models.CharField(max_length=20)),
                ('a4', models.DateField()),
                ('a5', models.TimeField()),
                ('a6', models.CharField(max_length=300)),
            ],
        ),
    ]
